version: "3.8"

services:
  app:
    build: .
    expose:
      - "8000"   # expose only inside docker network, not directly to host
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      - CLIENT_URL=http://localhost:5173
      - PORT=8000
      - JWT_SECRET=t43jofijsfu9e0
      - MONGO_URI=mongodb://mongo:27017/mydatabase
      - REDIS_HOST=redis
      - ADMIN_EMAIL=rohitagrawal7974@gmail.com
      - ADMIN_PASSWORD=rohit123
    depends_on:
      - mongo
      - redis

  mongo:
    image: mongo:6
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

  redis:
    image: "redis:alpine"
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data

  nginx:
    image: nginx:latest
    ports:
      - "8000:80"   # expose nginx to host
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - app

volumes:
  mongo-data:
  redis-data:
