version: "3.8"

services:
  app:
    build: .
    expose:
      - "8000"   
    volumes:
      - .:/app
      - /app/node_modules
  
    depends_on:
      - mongo
      - redis

  mongo:
    image: mongo:6
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

  redis:
    image: "redis:alpine"
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data

  nginx:
    image: nginx:latest
    ports:
      - "8000:80"   
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - app

volumes:
  mongo-data:
  redis-data:
